/*CREATE USER trms
IDENTIFIED BY qwerty
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to trms;
GRANT resource to trms;
GRANT create session TO trms;
GRANT create table TO trms;
GRANT create view TO trms;
*/
--DROP TABLE DIRECT_SUPERVISOR;




DROP TABLE REIMBURSEMENT;
DROP TABLE EVENT_TYPE;
DROP TABLE GRADINGFORMAT;
DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEETYPE;
DROP TRIGGER EMPLOYEE_ON_INSERT;
DROP TRIGGER REIMBURSEMENT_ON_INSERT;
DROP SEQUENCE EMPLOYEE_SEQUENCE;
DROP SEQUENCE REIMBURSEMENT_SEQUENCE;


CREATE TABLE EMPLOYEETYPE(
    
    EMPTYPE_ID integer NOT NULL, -- foreign key to employee
    EMPTYPE_NAME varchar2(50) NOT NUlL, 
    
    CONSTRAINT PK_EMPTYPEID PRIMARY KEY (EMPTYPE_ID) 
);


CREATE TABLE EMPLOYEE (
    EMPLOYEEID number NOT NULL,
    FIRSTNAME varchar2(100) NOT NULL,
    LASTNAME varchar2(100) NOT NULL,
    PASSWD varchar2(100) NOT NULL,
    USERNAME varchar2(100) NOT NULL,
    EMAIL varchar2(50) NOT NULL,
    SUPERVISOR integer,
    DEPT_HEAD integer,
    BENCO integer,
    AMOUNT_USED number NOT NULL,
    EMPLOYEETYPEID integer NOT NULL,

    
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEEID)
);

CREATE TABLE EVENT_TYPE(
    EVTTYPE_ID INTEGER NOT NULL,
    EVTTYPE_NAME VARCHAR2(50) NOT NULL,
    EVTTYPE_COVERAGE NUMBER NOT NULL,
    
    CONSTRAINT PK_EVTTYPE PRIMARY KEY (EVTTYPE_ID)
);


CREATE TABLE GRADINGFORMAT(
    GF_ID INTEGER NOT NULL,
    GF_TYPE VARCHAR2(50) NOT NULL,
    GF_PASSING NUMBER NOT NULL,
    
    CONSTRAINT PK_GFID PRIMARY KEY (GF_ID)
    
);


/*
CREATE TABLE EVENT(
    EVT_ID INTEGER NOT NULL,
    EVTTYPE_ID INTEGER NOT NULL,
    RID INTEGER NOT NULL,
    LOCAT VARCHAR2(50) NOT NULL,
    DESCR VARCHAR2(200) NOT NULL,
    DATE_START DATE NOT NULL,
    HOURS NUMBER NOT NULL,
    COST_AMT NUMBER NOT NULL,
    REASON VARCHAR2(200) NOT NULL,
    TIME_MISSED NUMBER NOT NULL,
    COMPLETED INTEGER NOT NULL,
    GF_ID INTEGER NOT NULL,
    
    CONSTRAINT PK_EVTID PRIMARY KEY (EVT_ID)
);
*/
CREATE TABLE REIMBURSEMENT(
    RID INTEGER NOT NULL,
    COST_AMT number NOT NULL,
    EMPLOYEEID INTEGER NOT NULL,
    SUPER_APR INTEGER NOT NULL,
    DEPT_ARR INTEGER NOT NULL,
    BENCO_APR INTEGER NOT NULL, 
    EVTTYPE_ID INTEGER NOT NULL,
    LOCAT VARCHAR2(50) NOT NULL,
    DESCRIPT VARCHAR2(200) NOT NULL,
    DATE_START DATE NOT NULL,
    EVT_TIME VARCHAR2(4) NOT NULL,
    REASON VARCHAR2(200) NOT NULL,
    GF_ID INTEGER NOT NULL,
 
    CONSTRAINT PK_REIMBURSEMENT PRIMARY KEY (RID)
);


--employeetype
--event table- (id, type, coverage)
--grading format table(id, type, passing)
--file table(fileid, rid, filepath, file_desc)





ALTER TABLE REIMBURSEMENT ADD CONSTRAINT FK_EMPLOYEEID
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE (EMPLOYEEID);
    
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_DEPTHEAD
    FOREIGN KEY (DEPT_HEAD) REFERENCES EMPLOYEE (EMPLOYEEID);
    
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_SUPERVISOR
    FOREIGN KEY (SUPERVISOR) REFERENCES EMPLOYEE (EMPLOYEEID);
    
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEETYPEID
    FOREIGN KEY (EMPLOYEETYPEID) REFERENCES EMPLOYEETYPE (EMPTYPE_ID);
    
ALTER TABLE REIMBURSEMENT ADD CONSTRAINT FK_EVTTYPE
    FOREIGN KEY (EVTTYPE_ID) REFERENCES EVENT_TYPE (EVTTYPE_ID);
    
ALTER TABLE REIMBURSEMENT ADD CONSTRAINT FK_GFID
    FOREIGN KEY (GF_ID) REFERENCES GRADINGFORMAT (GF_ID);




--create triggers and sequences
CREATE SEQUENCE employee_sequence
    MINVALUE 1
    MAXVALUE 99999999
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE OR REPLACE TRIGGER employee_on_insert
  BEFORE INSERT ON EMPLOYEE
  FOR EACH ROW
BEGIN
  SELECT employee_sequence.nextval
  INTO :new.EMPLOYEEID
  FROM dual;
END;
/


CREATE SEQUENCE reimbursement_sequence
    MINVALUE 1
    MAXVALUE 99999999
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE OR REPLACE TRIGGER reimbursement_on_insert
  BEFORE INSERT ON REIMBURSEMENT
  FOR EACH ROW
BEGIN
  SELECT reimbursement_sequence.nextval
  INTO :new.RID
  FROM dual;
END;
/

--INSERT VALUES-----------------------------------------------------------------

INSERT INTO EMPLOYEETYPE
VALUES(1, 'EMPLOYEE');
INSERT INTO EMPLOYEETYPE
VALUES(2, 'DIRECT_SUPERVISOR');
INSERT INTO EMPLOYEETYPE
VALUES(3, 'DEPARTMENT_HEAD');
INSERT INTO EMPLOYEETYPE
VALUES(4, 'BENEFIT_COORDINATOR');

INSERT INTO EVENT_TYPE
VALUES(1, 'UNIVERSITY', 80);
INSERT INTO EVENT_TYPE
VALUES(2, 'SEMINAR', 60);
INSERT INTO EVENT_TYPE
VALUES(3, 'CERTPREP', 75);
INSERT INTO EVENT_TYPE
VALUES(4, 'CERTIFICATION', 100);
INSERT INTO EVENT_TYPE
VALUES(5, 'TECHTRAINING', 90);
INSERT INTO EVENT_TYPE
VALUES(6, 'OTHER', 30);


INSERT INTO GRADINGFORMAT
VALUES(1, 'LETTER GRADE', 70);
INSERT INTO GRADINGFORMAT
VALUES(2, 'PASS FAIL', 50);

INSERT INTO EMPLOYEE
VALUES(1, 'Brandon', 'Jones', 'eza', 'brandj', 'bradj@email.com', NULL, NULL, NULL, 1000, 4);
INSERT INTO EMPLOYEE
VALUES(2, 'Ben', 'Jo', 'asd', 'benjo', 'benjo@email.com', NULL, NULL, 1, 1000, 3);
INSERT INTO EMPLOYEE
VALUES(3, 'Brad', 'El', 'asd', 'bradel', 'bradel@email.com', NULL, 2 , 1, 1000, 2);
INSERT INTO EMPLOYEE
VALUES(4, 'Kyle', 'Bo', 'asd', 'kylebo', 'kylebo@email.com', 3, 2, 1, 1000, 1);
INSERT INTO EMPLOYEE
VALUES(5, 'Mike', 'Hu', 'asd', 'mikehu', 'mikehu@email.com', 3, 2, 1, 1000, 1);
INSERT INTO EMPLOYEE
VALUES(6, 'Don', 'Ca', 'asd', 'donca', 'donca@email.com', 3, 2, 1, 1000, 1);




commit;